### ISSUE TITLE
Material Node Frames buggy 

### ISSUE THREAD

**Issue by leonard7e** [appleseedhq/blenderseed#401] opened 2019-02-27 12:23 UTC
Ubuntu Linux (18.04)
Blender 2.79b (suitable for appleseed)

--
Dear Developers.
Pack nodes into a frame seems buggy in Appleseed Material nodes.
Using a frame inside Material node tree creates Strange behaviours on Render (F12) or Interactive Render 

How to reproduce:

- Create simple material.Default uses disney node. Lets keep disney node.
- Pack disney node into a frame using Strg+J 
- Hit interactive rendering or render (F12).

After hit "Render" (F12), I get a transparent 'empty' image.  Console shows NodeFrame lacks node_type.

```
Exception ignored in: <bound method RenderAppleseed.__del__ of <bpy_struct, RenderAppleseed invalid>>
Traceback (most recent call last):
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 104, in __del__
    self.__stop_rendering()
ReferenceError: StructRNA of type RenderAppleseed has been removed
Traceback (most recent call last):
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 133, in render
    self.__render_final(scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 222, in __render_final
    scene_translator.translate_scene()
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/scene.py", line 212, in translate_scene
    self._do_create_entities(self.bl_scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/group.py", line 225, in _do_create_entities
    x.create_entities(scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/materials.py", line 115, in create_entities
    self.__set_shader_group_parameters(scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/materials.py", line 179, in __set_shader_group_parameters
    if shader.node_type == 'osl_surface':
AttributeError: 'NodeFrame' object has no attribute 'node_type'

```

On Interactive Rendering, Blender UI got messed up. Again, console shows NodeFrame lacks node_type.
```

Exception ignored in: <bound method RenderAppleseed.__del__ of <bpy_struct, RenderAppleseed invalid>>
Traceback (most recent call last):
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 104, in __del__
    self.__stop_rendering()
ReferenceError: StructRNA of type RenderAppleseed has been removed
Traceback (most recent call last):
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 137, in view_update
    self.__start_interactive_render(context)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 287, in __start_interactive_render
    self.__interactive_scene_translator.translate_scene()
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/scene.py", line 212, in translate_scene
    self._do_create_entities(self.bl_scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/group.py", line 225, in _do_create_entities
    x.create_entities(scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/materials.py", line 115, in create_entities
    self.__set_shader_group_parameters(scene)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/translators/materials.py", line 179, in __set_shader_group_parameters
    if shader.node_type == 'osl_surface':
AttributeError: 'NodeFrame' object has no attribute 'node_type'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 145, in view_draw
    self.__draw_pixels(context)
  File "/home/leonard/.config/blender/2.79/scripts/addons/blenderseed/render/__init__.py", line 358, in __draw_pixels
    self.__tile_callback.draw_pixels(0, 0, width, height)
AttributeError: 'NoneType' object has no attribute 'draw_pixels'

location: <unknown location>:-1

location: <unknown location>:-1

```

**Comment by jdent02** [comment] 2019-02-27 12:44
Hi Leonard.  Thanks for the report.  I can see where the problem is and I'll get it fixed ASAP.

**Comment by leonard7e** [comment] 2019-02-27 12:55
Hi Jonathan,
thank you for your help.

**Comment by jdent02** [comment] 2019-02-27 12:58
#402

**Comment by dictoon** [comment] 2019-03-01 22:41
A fix was committed.

**Closed by dictoon** 2019-03-01 22:41 UTC
Labels: Bug
