### ISSUE TITLE
Crash when trying to activate blenderseed 0.8.0 preview 4

### ISSUE THREAD

**Issue by blademaster7** [appleseedhq/blenderseed#242] opened 2018-04-21 09:11 UTC
Hi,
I tried to activate the plugin in 2.79b, and I get this error, in the image below.

![appleseed_19](https://user-images.githubusercontent.com/34082930/39082491-6f2c23e2-4543-11e8-93f8-fea075bb9428.gif)

**Comment by jdent02** [comment] 2018-04-21 12:02
Hi blademaster.  Did you have blenderseed installed on your system before?

**Comment by jdent02** [comment] 2018-04-21 14:11
The problem usually comes from two different addons trying to use the same class name, but I can't image any other addon uses the term 'appleseed'.  How did you install it?

**Comment by blademaster7** [comment] 2018-04-22 10:35
Hi,
That makes sense.

I initially placed the extracted folder in the add-ons directory.

This time I removed all traces of blendseed that I could find, and did an install from the zip file, and I got the message below.

[appleseed_19_zip_install.gif]

Thanks for your asistance, it's much appreciated.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dictoon** [comment] 2018-04-22 10:51
Looks like your screenshot wasn't attached properly.

**Comment by dictoon** [comment] 2018-04-22 10:52
FYI we can reproduce the problem and we are investigating. Sorry for the troubles, and thanks for your patience!

**Comment by blademaster7** [comment] 2018-04-22 12:57
Hi dictoon,
I'm glad you can reproduce it. No need to apologize, stuff happens. The main thing is you guys are heading in the right direction. Thanks for all the assistance, I look forward to trying 1.9.
Have a great day.

**Comment by jdent02** [comment] 2018-04-22 13:03
Can you try downloading the latest master from the ‘code’ page?  When you download, be sure to remove the -master suffix from the folder first.

**Comment by blademaster7** [comment] 2018-04-22 13:46
Success! 
I am looking at a white cube on a white plain in rendered view. Now to go and play. Gentlemen, thank you for such a fast response. Amazing service.

**Comment by dictoon** [comment] 2018-04-22 13:55
Good to hear that it's working now!

It seems that we don't know what the error was, though? Do I understand correctly that the blenderseed preview you downloaded from @jdent02's post on BlenderArtists does _not_ work, while a clone of `master` does work?

**Comment by jdent02** [comment] 2018-04-22 15:30
That would suck....

Sent from my iPhone

On Apr 22, 2018, at 8:55 AM, François Beaune <notifications@github.com<mailto:notifications@github.com>> wrote:


Good to hear that it's working now!

It seems that we don't know what the error was, though? Do I understand correctly that the blenderseed preview you downloaded from @jdent02<https://github.com/jdent02>'s post on BlenderArtists does not work, while a clone of master does work?

**Comment by blademaster7** [comment] 2018-04-22 21:49
It seems to be the case. It works on both machines. Win 7 x 64, blender 2.79b. The preview definitely does not. I tried multiple times.

![appleseed_render](https://user-images.githubusercontent.com/34082930/39100282-f8635368-4676-11e8-85e8-915959c0c6c9.png)

**Comment by dictoon** [comment] 2018-04-23 09:52
There aren't fundamental differences between the ZIP file linked in John's post on BA and the ZIP file that can be downloaded from GitHub, just a few bug fixes:

![image](https://user-images.githubusercontent.com/321290/39119643-ab47e7ee-46ec-11e8-8527-9310235dc85e.png)

So maybe one of this bug fix was critical? The only thing I can see is that the plugin used to crash when the path to appleseed's binaries was not set.

**Comment by blademaster7** [comment] 2018-04-24 22:49
I could never get the preview to check. As soon as I clicked to enable the plugin, the error message would pop up. It was never enabled at any stage. The master one on the other hand, enabled as soon as I clicked on the check-box, on both machines.

**Comment by blademaster7** [comment] 2018-04-25 11:07
No problem at all.

**Comment by jdent02** [comment] 2018-04-25 12:34
Here it is:
[blenderseed-0.8.0-preview6.zip](https://github.com/appleseedhq/blenderseed/files/1946974/blenderseed-0.8.0-preview6.zip)

**Comment by blademaster7** [comment] 2018-04-25 13:19
Ok, what I'm about to write applies to two different machines. The same thing occurred. I removed the master version that worked. I then opened up Blender to make sure the Appleseed plugin did not show up. I then copied the preview6 file to the add-ons directory. I opened up Blender, went to add-ons tab. The Appleseed plugin was there. I clicked to enable and Blender freezes. See image below. You can see the plugin is not checked.
![not_responding](https://user-images.githubusercontent.com/34082930/39247943-56ce6504-488a-11e8-82f0-9b3b287e4409.gif)

I then restart blender, and go the add-ons tab, and the plugin is checked. I decide to check if the plugin will work. I select it from the drop down menu. And hit Render Frame. Bingo, it's starts to render. See below.
![successful_render](https://user-images.githubusercontent.com/34082930/39248106-c07ab520-488a-11e8-9ae4-2072c49626b5.gif)

I'm going try the process again to see if I can reproduce Blender hanging on Appleseed activation, and will report how I go. I hope this helps in some measure. I will also try the "install from file" method as well.

**Comment by jdent02** [comment] 2018-04-25 14:18
How long did the 'hang' go on before you closed Blender?  There's a lot of stuff blenderseed does when it's first enabled and if it gets caught up in your system doing something else it can appear to hang.

Good that it does work though.  FYI I only use addons from the location where 'install from file' puts them (AppData/roaming/Blender Foundation)

BTW is your copy of Blender installed or are you using a self contained copy (the .zip download)?  Another one of our guys had similar behavior to yours when he was using a self contained Blender version alongside an installed one.

**Comment by blademaster7** [comment] 2018-04-26 01:37
Will do thanks. To answer your questions though. I let it hang for about 5-10min, as I went and made a cup of coffee. I only use the self contained versions, though AppData directory structure is there so plugins can install there. Attached is the command line output, fyi.

[output.txt](https://github.com/appleseedhq/blenderseed/files/1949337/output.txt)

**Comment by dictoon** [comment] 2018-04-26 09:02
> Turns out I made a mistake in one of my recent commits and that's what's causing that freezup you're seeing.

Oh ok, that explains why I got Blender to hang the other day. Cool.

**Comment by jdent02** [comment] 2018-04-28 13:04
blademaster can you try the latest master branch?  This issue should be fixed

**Comment by dictoon** [comment] 2018-04-28 13:11
@blademaster7 Even better, could you try the latest preview? You can download it here: https://www.dropbox.com/s/oy8dzosahot3sjf/blenderseed-0.8.0-beta-preview7.zip?dl=0

**Comment by blademaster7** [comment] 2018-04-28 14:33
Hi dictoon, 
Thanks for the updated file. I can confirm preview7 worked on the two machines. using both installation methods. If you need any more testing, let me know. Thanks for all your efforts.

**Comment by dictoon** [comment] 2018-04-28 14:39
Thank you! Closing this ticket then.

**Closed by dictoon** 2018-04-28 14:39 UTC
Labels: Bug
